/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.parisnanterre.devopsch3.backend;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    

    public static void main(String[] args) {
        
    }
}
